# Add 'repo' label to any root file changes
repo:
  - changed-files:
      - any-glob-to-any-file: "*"

# Add 'ci' label to any changes in the '.github' directory
ci:
  - changed-files:
      - any-glob-to-any-file:
          # - .github/actions/*
          # - .github/actions/*/**
          - .github/auto_assign.yml
          - .github/auto_assign.yml/**
          - .github/dependabot.yml
          - .github/dependabot.yml/**
          - .github/workflows/*
          - .github/workflows/*/**
          - .trunk/*
          - .trunk/*/**

# Add 'container' label to any changes in 'compose.yml' or 'Dockerfile'
# container:
#   - changed-files:
#       - any-glob-to-any-file:
#           - "*/**/compose.yml"
#           - "*/**/Dockerfile"
#           - "*/compose.yml"
#           - "*/Dockerfile"

# Add 'chart' label to any changes in the 'chart' directory
# chart:
#   - changed-files:
#       - any-glob-to-any-file:
#           - chart/*
#           - chart/*/**

# Add 'toolchain' label to any changes in the 'scripts' or 'tools' directories
# toolchain:
#   - changed-files:
#       - any-glob-to-any-file:
#           - scripts/*
#           - scripts/*/**
#           - tools/*
#           - tools/*/**
#           - hack/*.sh

# Add 'go' label to any changes in the 'go' directory
# go:
#   - changed-files:
#       - any-glob-to-any-file:
#           - go/*
#           - go/*/**

# Add 'python' label to any changes in the 'python' directory
# python:
#   - changed-files:
#       - any-glob-to-any-file:
#           - python/*
#           - python/*/**

# Add 'rust' label to any changes in the 'rust' directory
# rust:
#   - changed-files:
#       - any-glob-to-any-file:
#           - rust/*
#           - rust/*/**

# Add 'swift' label to any changes in the 'swift' directory
# swift:
#   - changed-files:
#       - any-glob-to-any-file:
#           - swift/*
#           - swift/*/**

# Add 'docs' label to any changes in the 'docs' directory
docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*
          - docs/*/**
          - README.md
